version: '3'

services:
  app:
    build: ./docker/app
    depends_on:
      - db
    volumes:
      - .:/var/www:cached

  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lara_db
      MYSQL_USER: user01
      MYSQL_PASSWORD: Katou0406
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - laravel-db-data:/var/lib/mysql

volumes:
  laravel-db-data:
    driver: local
